# Pull the GitHub Runner Scale Set Controller OCI Artifact
# and convert it to a standard Helm tar.gz file and push it
# to this repository for use with tools like Kustomize.

name: GitHub Runner Scale Set Controller Helm Builder
run-name: ${{github.actor}} - GitHub Runner Scale Set Controller Helm Builder

on:
  push:
    branches:
    - main

env:
  GHRSS_VERSION: 0.3.0 # https://github.com/actions/actions-runner-controller/releases/tag/gha-runner-scale-set-0.3.0
  CR_VERSION: 1.6.0 # https://github.com/helm/chart-releaser/releases/tag/v1.6.0

jobs:
  build-and-push-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3          

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            skopeo wget file git
      # - name: Install Helm
      #   run: |
      #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      # https://github.com/helm/chart-releaser
      - name: install chart-releaser
        run: |
          wget -qO- https://github.com/helm/chart-releaser/releases/download/v${{env.CR_VERSION}}/chart-releaser_${{env.CR_VERSION}}_linux_amd64.tar.gz | tar -xvz -C ./
      - name: Copy and Download the OCI Artifact
        run: |
          mkdir -p arc
          skopeo copy \
            docker://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set:${{env.GHRSS_VERSION}} \
            dir:./arc

      - name: Find and extract the Helm Chart
        run: |
          for file in $(find arc -type f); do  
            if [[ $(file $file --mime-type | awk '{print $2}') == "application/gzip" ]]; then
              tar -zxvf $file
              break
            fi
          done
      
      - name: Package the GitHub Action Runner Scale Set Helm Chart
        run: |
          ./cr package gha-runner-scale-set/

      - name: Upload Helm Chart to GitHub
        run: |
          ./cr upload \
            --owner ${{github.actor}} \
            --git-repo ${{github.event.repository.name}} \
            --packages-with-index \
            --token ${{secrets.SECRET_TOKEN}} \
            --skip-existing \
            --push

      - name: Set Git User values
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

        # https://github.com/helm/chart-releaser/issues/187
      - name: Create and push the Helm Index to GitHub
        run: |
          mkdir -p .cr-index && \
          git fetch --all && \
          ./cr index \
          --owner ${{github.actor}} \
          --git-repo ${{github.event.repository.name}} \
          --packages-with-index \
          --token ${{secrets.SECRET_TOKEN}} \
          --index-path . \
          --push
